### ISSUE TITLE
about micrometer

### ISSUE THREAD

**Issue by HelloTo4x** [quarkiverse/quarkus-micrometer-registry#177]
Hi, i am reading your project, why do you use Micrometer for collecting metric ? why don't you use Grafana + Prometheus to collect log and metric ? Do you know about pros and cons of Micrometer, can you tell me about it

**Comment by ebullient** [comment]
Micrometer is a library that abstracts collection of metrics that can be sent to multiple observability backends.

The core micrometer extension is part of Quarkus, as is the quarkus-micrometer-prometheus-registry, which gathers telemetry data and produces an endpoint that prometheus can scrape to gather data that you can then visualize in Grafana.

But many businesses choose to use observability solutions from vendors (like Datadog), and the Quarkus extensions in this project support those variants.
