### ISSUE TITLE
otlp registty seems to break the opentelemetry traces implementation

### ISSUE THREAD

**Issue by tobiasvdp** [quarkiverse/quarkus-micrometer-registry#203]
Hi, have noticed that opentelemetry completely stops functioning when adding the otlp exporter. 
Would have have any insights in why this happens? 
(Completely cancels out opentelemetry, not sending traces and not intercepting logs to console)

Kind regards

```
        <!-- Metrics-->
        <dependency>
            <groupId>io.quarkiverse.micrometer.registry</groupId>
            <artifactId>quarkus-micrometer-registry-otlp</artifactId>
            <version>2.11.0</version>
        </dependency>

        <!-- Tracing -->
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-opentelemetry-exporter-otlp</artifactId>
            <version>2.12.0.CR1</version>
        </dependency>
```

Properties file
```
quarkus.opentelemetry.enabled=true
quarkus.opentelemetry.tracer.sampler=on
quarkus.opentelemetry.tracer.exporter.otlp.endpoint=http://opentelemetry-collector:4317
quarkus.opentelemetry.tracer.exporter.otlp.headers=Authorization=Bearer my_secret
quarkus.opentelemetry.propagators=b3,b3multi,baggage,jaeger,ottrace,tracecontext,xray
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n  

//quarkus.micrometer.export.otlp.enabled=true
//quarkus.micrometer.export.otlp.url=http://opentelemetry-collector:4317/v1/metrics
//quarkus.micrometer.export.otlp.resourceAttributes=
```

**Comment by tobiasvdp** [comment]
mmm seems to do it for all others also. Might just be a larger issue on opentelemetry side

**Comment by ebullient** [comment]
I suspect the configuration of this extension conflicts with configuration of the otel sdk managed by core. We're in the middle of a big round of improvements for quarkus opentelemetry behaviors.. will add this to the pile.
cc @brunobat

**Comment by tobiasvdp** [comment]
Can add to this that it works for v2.11.x
Apparently only starts failing starting from 2.12.0.CR1

Kind regards
Tobias

**Comment by brunobat** [comment]
Sorry, this got buried in my notifications. 
The OTLP exporter for OTel has been moved, [after 2.14](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.14#opentelemetry-exporters-moved), to the main OTel extension as the default exporter. 
Will take a look at this.

**Comment by brunobat** [comment]
Tested this with the otel-collector v0.57.2 and latest v0.63.1 and it worked for me with the latest Quarkus 2.14.0.CR1. Got metrics and traces.
