### ISSUE TITLE
Metric name for HTTP Client

### ISSUE THREAD

**Issue by andreas-trvlk** [quarkiverse/quarkus-micrometer-registry#207]
Hi. I am enabling `quarkus.micrometer.binder.http-client.enabled` on my project. But, I am not sure what the metric name is. FYI, the metrics are sent to the datadog. It is expected to monitor Quarkus REST Client.

**Comment by andreas-trvlk** [comment]
Also, I think it doesn't support percentile? I cannot see percentile metric.

**Comment by ebullient** [comment]
It can be useful to turn on prometheus (too) so you have a local endpoint to explore to see what is being produced (with the caveat that each registry has their own naming conventions and calculations.

For http requests, the base that micrometer uses is `http.server.requests` and `http.client.requests`. 

Quarkus does not do any modifications to the micrometer libraries that support the various backend implementations, for datadog, you are subject to what each of the following backends chooses to do (depending on which you use)

- [Using the Datadog API](https://micrometer.io/docs/registry/datadog#_direct_to_datadog_api_approach)
- [Using statsd](https://micrometer.io/docs/registry/datadog#_through_dogstatsd_approach)

If you have additional questions about how the micrometer datadog registry implementation works, I recommend heading to the [Micrometer Slack](https://join.slack.com/t/micrometer-metrics/shared_invite/zt-ewo3kcs0-Ji3aOAqTxnjYPEFBBI5HqQ).
