### ISSUE TITLE
Unrecognized configuration key "quarkus.micrometer.export.otlp" was provided

### ISSUE THREAD

**Issue by AndreasPetersen** [quarkiverse/quarkus-micrometer-registry#227]
According to [the docs](https://quarkiverse.github.io/quarkiverse-docs/quarkus-micrometer-registry/dev/micrometer-registry-otlp.html) `quarkus.micrometer.export.otlp` config property.

Using 

```
implementation 'io.quarkiverse.micrometer.registry:quarkus-micrometer-registry-otlp:2.12.0'
```

with Quarkus version 2.14.2, I get the following WARN in console output:

```
2022-12-05 15:51:38,383 WARN  [io.qua.config] (Quarkus Main Thread) {} Unrecognized configuration key "quarkus.micrometer.export.otlp" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

application.properties:

```
quarkus.micrometer.export.otlp=url=http://localhost:4318
```

Java and Gradle version:
```
./gradlew --version

------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.17 (Eclipse Adoptium 11.0.17+8)
OS:           Windows 10 10.0 amd64
```

**Comment by luneo7** [comment]
Dunno if you figured it out, but that property is being wrongly set, https://quarkiverse.github.io/quarkiverse-docs/quarkus-micrometer-registry/dev/micrometer-registry-otlp.html , `quarkus.micrometer.export.otlp` is a map, so you need to set it as `quarkus.micrometer.export.otlp.url=http://localhost:4318`, since `url` is a key inside the `otlp` map and `http://localhost:4318` is the value for that key =]

**Comment by AndreasPetersen** [comment]
Great, thanks. Maybe it's just me, but I didn't think this was immediately obvious in the documentation. Perhaps an example would be in order?

**Comment by ebullient** [comment]
> Great, thanks. Maybe it's just me, but I didn't think this was immediately obvious in the documentation. Perhaps an example would be in order?

Would love for you to rough one in... this is a case where your perspective is better than ours.
