### ISSUE TITLE
How can i provide the Datadog API Key via Environment Variable?

### ISSUE THREAD

**Issue by timmhirsens** [quarkiverse/quarkus-micrometer-registry#238]
Hey,
i want to provide the Datadog API Key via environment variable since this is a secret. I tried numerous things now but neither seem to work. Any hints?

```bash
export QUARKUS_MICROMETER_EXPORT_DATADOG_API_KEY=122344557438294
export QUARKUS_MICROMETER_EXPORT_DATADOG_APIKEY=122344557438294
export QUARKUS_MICROMETER_EXPORT_DATADOG="API_KEY=122344557438294"
export MICROMETER_EXPORT_DATADOG_API_KEY=122344557438294
export MICROMETER_EXPORT_DATADOG_APIKEY=122344557438294
```

**Comment by brunobat** [comment]
Hi @timmhirsens.
This property shouldn't have bee set as camel case... Please try:
QUARKUS_MICROMETER_EXPORT_DATADOG_API-KEY

**Comment by timmhirsens** [comment]
Hey @brunobat 
Thanks for the swift reply. I don’t think environment variables can have hyphens/dashes, though? At least not without workarounds

**Comment by brunobat** [comment]
You are right... I'm confusing it with the system property convention.

**Comment by timmhirsens** [comment]
In case someone does have the same issue as me, i worked around this by defining 
```
quarkus.micrometer.export.datadog.api-key=${datadog.apikey}
```
in the `application.properties` and then setting
```
DATADOG_APIKEY=<theapikey>
```
in the runtime environment.
