### ISSUE TITLE
Better way to get metrics from dynamic Agroal DataSources ?

### ISSUE THREAD

**Issue by laurentperez** [quarkiverse/quarkus-micrometer-registry#48]
Hello

We have dynamic Quarkus Agroal datasources (as in, multitenant discovered at runtime).
Our code creates `io.agroal.pool.DataSource#DataSource` at startup or at some refresh interval, configuration is read from a database, not from a properties file. Basically we're following https://quarkus.io/guides/hibernate-orm#programmatically-resolving-tenants-connections

By default, no metrics of our datasources are exported on /q/metrics. I believe this is because the `consumer/producer` mechanism https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/metrics/AgroalMetricsRecorder.java is set at runtime init, by the processor at https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalMetricsProcessor.java

So, to register metrics at runtime, I did something like this, which is ugly, I'd like to know what you guys are thinking of it. I think you understand what I'm trying to do : do not reimplement all builders of https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/metrics/AgroalMetricsRecorder.java#L37 since the code already exists and can evolve.

        val ds = DataSource(dsConfig) // our dynamic datasource, server IP, port, pool size, etc.
        val mf = MicrometerMetricsFactory(MicrometerConfig(), Metrics.globalRegistry) // the config is false not read from @ConfigRoot, but it works
        mf.builder("agroal.foo.acquire")
            .description("Foo")
            .tag("datasource", "$ds-$serverName")
            .buildGauge(ds.metrics::acquireCount); // curl  http://localhost:8080/q/metrics|grep agroal|grep foo

Is there a better way to do this ? `AgroalMetricsProcessor` has a `@BuildStep` with `MetricsFactoryConsumerBuildItem`

Do you think at build time, I could discover my datasources configuration to get the automatic binding from the `AgroalMetricsProcessor/AgroalMetricsRecorder` ?

**Comment by ebullient** [comment]
You don't need to emulate what Agroal is currently doing at all. The Agroal extension is currently hedging (doing something that would work w/ either metrics extension). 

If you are doing initialization later, you might model more closely after what Hibernate does here: https://github.com/hibernate/hibernate-orm/tree/main/hibernate-micrometer/src/main/java/org/hibernate/stat

Or other database related MeterBinder impls:
https://github.com/micrometer-metrics/micrometer/tree/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder

You'll want to define a MeterBinder for Agroal datasources, that you can then "bind" to the injected registry later, e.g. you have the MeterBinder returned by a CDI @Produces method after some configuration is read. 
The Micrometer extension will call the `bindTo` method on discovered MeterBinders when things are ready to go.

**Comment by laurentperez** [comment]
Ok I think I understand a little better. But I'm not sure I understand the returned by a CDI Produces part.

My dataSources are initialized at boot time (quarkus StartupEvent) but they are also periodically destroyed, refreshed at runtime, because we do some dynamic stuff on dataSources. For example, we have cases where the jdbc://ip.addresse of the RDBMS is modified at runtime.
We put them in a Map, say "mapDb".

Why would I need to return the binder from a Produces ? Looking at https://github.com/hibernate/hibernate-orm/blob/main/hibernate-micrometer/src/main/java/org/hibernate/stat/HibernateMetrics.java statistics is initialized in the constructor.

I'm not sure I understand the bindTo lifecycle. My "mapDB" is not known until boot time, so I'm unsure how to plug it in the binder.

**Comment by ebullient** [comment]
in that case, have the MeterRegistry injected.. and bind metrics to the registry whenever. ;)

**Comment by ebullient** [comment]
It's somewhat up to you. The MeterBinder can be a good way to structure things.. but note the constructors on the Hibernate MeterBinder -- there isn't any fixed limit on when it can be constructed.

The Kafka binder that Quarkus uses is bound/removed using CDI events when producers/consumers show up and disappear...

**Comment by ebullient** [comment]
agroal is not using a meter binder directly.. it's using a quarkus core abstraction so that it can work with either micrometer or smallrye metrics. It is effectively being fed the registry via the consumer it defines at build time (called after the registry has been initialized)

**Comment by laurentperez** [comment]
Ok ; it's clearer

Our dataSources are not yet known at build time so I guess we can't benefit from https://github.com/quarkusio/quarkus/blob/454eeff2cf99a09bae266cf61f332a407da85084/extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalMetricsProcessor.java#L29 and the AggregatedDataSourceBuildTimeConfigBuildItem 

I'm closing this since we found a away to get to metrics at runtime

Thanks
