### ISSUE TITLE
NPE on test when deactivating stackdriver export

### ISSUE THREAD

**Issue by Thibaud-R** [quarkiverse/quarkus-micrometer-registry#85]
When running unit tests, I encoutered the message:
```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
...
Caused by: io.micrometer.core.instrument.config.validate.ValidationException: stackdriver.projectId was 'null' but it is required
	at io.micrometer.core.instrument.config.validate.Validated$Either.orThrow(Validated.java:366)
```
So, in order to avoid this error, I add the following configuration to disable stackdriver export when running tests:
%test.quarkus.micrometer.export.stackdriver.enabled=false

But I'm getting the following error:
```
java.lang.NullPointerException
	at io.quarkus.micrometer.runtime.binder.mpmetrics.CountedInterceptor.increment(CountedInterceptor.java:49)
	at io.quarkus.micrometer.runtime.binder.mpmetrics.CountedInterceptor.countedMethod(CountedInterceptor.java:33)
	at io.quarkus.micrometer.runtime.binder.mpmetrics.CountedInterceptor_Bean.intercept(CountedInterceptor_Bean.zig:325)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.arc.impl.InterceptedStaticMethods.aroundInvoke(InterceptedStaticMethods.java:24)
```

I also try to enter a fake projectId:
%test.quarkus.micrometer.export.stackdriver.projectId=toto
But the NPE error is still here.

**Comment by ebullient** [comment]
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
...
Caused by: io.micrometer.core.instrument.config.validate.ValidationException: stackdriver.projectId was 'null' but it is required
	at io.micrometer.core.instrument.config.validate.Validated$Either.orThrow(Validated.java:366)
	
-- that is an intentional error.

**Comment by Thibaud-R** [comment]
And this intentional error, block quarkus to start in a test envirnoment.
Is there a way to manage /deactivate stackdriver in a test environment ?

**Comment by ebullient** [comment]
I guess I don't understand how you are running. I have several tests that validate invalid configurations. So how are you running which tests in what mode?

**Comment by Thibaud-R** [comment]
Microprofile annotation are set on a rest method.
I add stackdriver dependency to export these metrics and other things to stackdriver in GCP env.
But when running my unit tests, stackdriver blocks quarkus to start.

**Comment by ebullient** [comment]
%dev.quarkus.micrometer.export.stackdriver.enabled=false
%test.quarkus.micrometer.export.stackdriver.enabled=false

You might need one or both of those. Alternately, add one of these as well: 

%dev.quarkus.micrometer.export.stackdriver.publish=false
%test.quarkus.micrometer.export.stackdriver.publish=false

**Comment by Thibaud-R** [comment]
Yes, that's what I tried after looking at the code (both enabled and publish). And quarkus starts.
But when running, I encoutered the NPE around methods with metrics:

java.lang.NullPointerException
	at io.quarkus.micrometer.runtime.binder.mpmetrics.CountedInterceptor.increment(CountedInterceptor.java:49)
	at io.quarkus.micrometer.runtime.binder.mpmetrics.CountedInterceptor.countedMethod(CountedInterceptor.java:33)
	at io.quarkus.micrometer.runtime.binder.mpmetrics.CountedInterceptor_Bean.intercept(CountedInterceptor_Bean.zig:325)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.arc.impl.InterceptedStaticMethods.aroundInvoke(InterceptedStaticMethods.java:24)

**Comment by ebullient** [comment]
ok. thinking this through, `quarkus.micrometer.export.stackdriver.enabled=false` is a build time / static attribute, so I don't think the profile is applied. The project-id and publish settings are runtime configuration, so those are picked up properly by the profile settings. 

So setting these will prevent stackdriver metrics from being published: 

%test.quarkus.micrometer.export.stackdriver.publish=false
%test.quarkus.micrometer.export.stackdriver.project-id=dummy

**Comment by ebullient** [comment]
I otherwise need a reproducer for the CounterInterceptor issue (in quarkus proper). I don't know what is null in that case.

**Comment by Thibaud-R** [comment]
With only publish and dummy projectId, I still encountered NPE.
mpRegistry is null.

**Comment by Thibaud-R** [comment]
And the rest method looks like:
````
@Timed(name = "messageTimer", description = "", unit = MetricUnits.MICROSECONDS)
public Uni<PosReturn> posApplication(@RestQuery("pn") String pn, @RestQuery("sn") String sn, String rawMessage)
````

**Comment by ebullient** [comment]
@Timed gets into the @Counted interceptor? That doesn't make sense. Some other method using the @Counted annotation is the culprit. 

As an aside. there is a known limitation with @Timed annotations and async methods: you likely aren't getting the duration you're expecting, see quarkusio/quarkus#15601. You're better off using the Timer API directly (while processing the Uni) to ensure you're capturing the right duration. I'm thinking about how to do this properly for Uni, but it isn't possible to do with Multi.

**Comment by Thibaud-R** [comment]
First using smallrye-metrics, I have @Counted and @Timed, but when using stackdriver, there was a warning indicating that @Counted was included in @Timed.
Thanks for the input on the limitation on @Timed, I will do it with the Timer API and reintroduce the @Counted annotation.

**Comment by ebullient** [comment]
Right, ok. Let me try to straighten this out:

If you had both `@Timed` and `@Counted`, the latter annotation should have been effectively dropped. It sounds like maybe that isn't happening properly, and I can test/verify that.

When you use a Timer, that does implicitly have a count, you don't need both. Also, if this is a normal rest endpoint, note that it is already timed (request/respose) out of the box: Look for http.server.requests.* with the matching URI.

**Comment by ebullient** [comment]
Did you previously have something like this, but on a Rest resource method? 
https://github.com/quarkusio/quarkus/blob/81530a5b81d082d49132eaa523b517b233ab4e20/integration-tests/micrometer-mp-metrics/src/main/java/io/quarkus/it/micrometer/mpmetrics/PrimeResource.java#L47

**Comment by Thibaud-R** [comment]
Yes exactly.

**Comment by ebullient** [comment]
ok. I've tried to reproduce this (see the PR), but I can't. If you have a suggestion for how to change that test so it fails the way yours does, that would help.

Can you otherwise clarify which versions you're using (of Quarkus, and of the Stackdriver registry extension)?

**Comment by Thibaud-R** [comment]
OK I will try to share a quarkus application and the according that fails.
Quarkus 2.0.1 or 2..0.2 and quarkus-micrometer-registry-stackdriver 2.0.0.CR3.

**Comment by Thibaud-R** [comment]
Sorry, I didn't have the time to work on a reproducer (but I will).

Question: is the creation of a custom MeterRegistry necessary or is the default one enough ?
(I'm starting to use micrometer - newbie question)

The NPE is always on the variable mpRegistry in the CountedInterceptor. 
this.mpRegistry.interceptorCounter...

And it also happens in a GCP environment with a valid stackdriver server ...

**Comment by ebullient** [comment]
default one should be enough... and I've not been able to recreate this. :(
